Stage/ProveVarie/Models/Carnet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProveVarie.Models
{
    public class Carnet
    {
        [Required]
        public int ID { get; set; }

        [Required(ErrorMessage = "Please enter a barcode for the carnet")]
        //[StringLength(13, MinimumLength = 13, ErrorMessage ="Please enter a valid barcode")]
        public string Barcode { get; set; }

        [Required(ErrorMessage = "Please enter a value")]
        //[Range(1,50, ErrorMessage = "Insert a value between 1 and 50")]
        public int Capacity { get; set; }


        public string Stockist { get; set; }

        public decimal Cost { get; set; }

        public DateTime? AssignmentDate { get; set; }

        public DateTime RegistrationDate { get; set; }

        public int? CostCenterID { get; set; }
        public CostCenter CostCenter { get; set; }
        public List<MealVoucher> MealVouchers { get; set; }
    }
}

Stage/ProveVarie/Controllers/CarnetController.cs
using ProveVarie.DataAccess;
using ProveVarie.Models;
using ProveVarie.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProveVarie.Controllers
{
    public class CarnetController : Controller
    {
        private AppDbContext context = new AppDbContext();
        private IRepository<Carnet> _repository;
        private IRepository<CostCenter> _costCentersRepository;
        //private List<string> _costCenters;
        //private List<CostCenter> _costCenters;

        public CarnetController()
        {
            _repository = new CarnetEntityFrameworkRepository(context);
            _costCentersRepository = new CostCenterEntityFrameworkRepository(context);
        }

        //public CarnetController(IRepository<Carnet> repository,
        //                        IRepository<CostCenter> costCentersRepository)
        //{
        //    _repository = repository;
        //    _costCentersRepository = costCentersRepository;
        //    //_costCenters = _costCentersRepository
        //    //    .FindAll();
        //        //.Select(x => x.Name).ToList();
        //}



        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Register()
        {
            var model = new Carnet();


            return View(model);
        }

        [HttpPost]
        public ActionResult Register(Carnet model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (model.ID == 0)
            {
                model.RegistrationDate = DateTime.Now;
                _repository.Insert(model);
            }


            return RedirectToAction(nameof(Register));
        }

        [HttpGet]
        public ActionResult Assignment()
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            //var model = new Carnet();

            ViewData["_costCenters"] = _costCentersRepository.FindAll();

            //return View(model);
            return View();
        }

        //[HttpGet]
        //public ActionResult Assignment(int id)
        //{
        //    Carnet model;

        //    if (id == 0)
        //    {
        //        model = new Carnet();

        //    }
        //    else
        //    {
        //        model = _repository.Find(id);
        //        if (model == null)
        //        {
        //            return HttpNotFound();
        //        }
        //    }

        //    ViewData["costCenters"] = _costCentersRepository.FindAll();

        //    return View(model);
        //    // popolare dropdown
        //    //var model = new CostCenterDropdown()
        //    //{
        //    //    //ID = carnet.ID,
        //    //    //Name = employee.Name,
        //    //    CostCenters = _costCenters
        //    //    .Select(x => new SelectListItem
        //    //{
        //    //    Value = x.ID.ToString(),
        //    //    Text = x.Name
        //    //})
        //    //};
        //}

        [HttpPost]
        public ActionResult Assignment(Carnet model, CostCenterDropdown list)
        {
            model.AssignmentDate = DateTime.Now;
            model.CostCenter = (CostCenter)list.CostCenters.Where(x => x.Selected);
            model.CostCenterID = model.CostCenter.ID;

            var result = _repository.Update(model);

            if (!result)
                return new HttpNotFoundResult("Non c'è un blocchetto corrispondente");

            return RedirectToAction(nameof(Assignment));
        }

    }
}

Stage/ProveVarie/Views/Carnet/Assignment.cshtml
@model Carnet

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/form.css")
@*@Scripts.Render("~/Scripts/Carnet.js")*@
@section Scripts
{
    <script src="@Url.Content("~/Scripts/Carnet.js")"></script>
}


@*@{
        var costCenters = (List<CostCenter>)ViewData["costCenters"];

        var selectListItems = costCenters.Select(x =>
        new SelectListItem
        {
            Value = x.ID.ToString(),
            Text = x.Name
        });
    }*@


<div class="container containerPad">
    <form method="post">
        <div class="form-group">
            @*@Html.LabelFor(model => model.CostCenter)
            @Html.DropDownListFor(m => m.CostCenter, selectListItems, "HR")*@
        </div>


        <div id="barcodes">
            <div class="form-group">

                @Html.LabelFor(model => model.Barcode)
                @Html.EditorFor(model => model.Barcode, new
            {
                htmlAttributes = new { @class = "form-control" }
            })

            </div>

        </div>
        <a class="plus"><span class="glyphicon glyphicon-plus-sign"></span></a><!--PER AGGIUNGERE ELEMENTO IMPLEMENTARE CON JS-->
        <!--input di prova-->
        @*<div class="form-group">
            <label class="control-label">Data</label>
            @Html.EditorFor(model => model.data_registrazione,  new { htmlAttributes = new { @class = "form-control", @type="date" } })
        </div>*@

        <div class="form-group">
            @Html.ActionLink(
                                                          "Annulla",
                                                          "Index",
                                                          "Home",
                                                          null,
                                                          new { @class = "btn btn-default" }
                                                          )
            @*<a class="btn btn-default" asp-controller="Carnet" asp-action="Secretary/Index">Annulla</a>*@
            <input type="submit" class="btn btn-primary" value="Registra" />
        </div>

    </form>
</div>

<!-- Modal -->
<div id="SaveModal" class="modal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content text-center">
            <div class="modal-header">
                <h4 class="modal-title">Assegnazione blocchetto</h4>
            </div>
            <div class="modal-body">
                <p>Vuoi Assegnare i blocchetti: @(Model.Barcode)?</p><!--poi implementare con js il get dei valori selezionati--->
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-primary" value="Ok" />
                @*@Html.ActionLink("Chiudi", "Index", "Home", null, new { @class = "btn btn-default" @data_dismiss = "modal" })*@
                <input id="closeBtn2" type="button" class="btn btn-primary" data-dismiss="modal" value="Chiudi">
            </div>
        </div>

    </div>
</div>

<div id="assignmentModal" class="modal fade in" role="dialog">
    <div class="modal-dialog" role="document">

        <!-- Modal content-->
        <div class="modal-content text-center">
            <div class="modal-header">
                <h4 class="modal-title">Conferma assegnazione</h4>
            </div>
            <div class="modal-body">
                <p>I blocchetti sono stati assegnati</p>
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-primary" value="Assegna" />
                <input id="closeBtn" type="button" class="btn btn-primary" data-dismiss="modal" value="Chiudi"><!--close-->
            </div>
        </div>

    </div>
</div>

Stage/ProveVarie/Views/Carnet/Register.cshtml
@model Carnet
@{
    ViewBag.Title = "Registrazione blocchetti";
}

<h2>@ViewBag.Title.</h2>

<h4>Registra un nuovo blocchetto</h4>
<hr />
<div class="container containerPad">
    <form method="post">
        <div class="form-group">
            @Html.LabelFor(model => model.Barcode)
            @Html.EditorFor(model => model.Barcode, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Stockist)
            @Html.EditorFor(model => model.Stockist, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Capacity)
            @Html.EditorFor(model => model.Capacity, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.ValidationMessageFor(model => model.VoucherNum, "", new { @class = "text-danger" })*@
            @*<select asp-for="VoucherNum" class="form-control" asp-items="cost"></select>*@
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Cost)
            @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })*@
        </div>

        <!--input di prova-->
        @*<div class="form-group">
                <label class="control-label">Data</label>
                @Html.EditorFor(model => model.data_registrazione,  new { htmlAttributes = new { @class = "form-control", @type="date" } })
            </div>*@

        <div class="form-group">
            @Html.ActionLink("Annulla", "Index", "Home", null, new { @class = "btn btn-default" })
            @*<a class="btn btn-default" asp-controller="Carnet" asp-action="Secretary/Index">Annulla</a>*@
            <input type="submit" class="btn btn-primary" value="Registra" />
        </div>
    </form>
</div>

<!-- Modal -->
<div id="SaveModal" class="modal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content text-center">
            <div class="modal-header">
                <h4 class="modal-title">Conferma registrazione</h4>
            </div>
            <div class="modal-body">
                <p>Vuoi registrare il blocchetto @(Model.Barcode)?</p>
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-primary" value="Ok" />
                @*@Html.ActionLink("Chiudi", "Index", "Home", null, new { @class = "btn btn-default" @data_dismiss = "modal" })*@
                <input id="closeBtn2" type="button" class="btn btn-primary" data-dismiss="modal" value="Chiudi">
            </div>
        </div>

    </div>
</div>

<div id="assignmentModal" class="modal fade in" role="dialog">
    <div class="modal-dialog" role="document">

        <!-- Modal content-->
        <div class="modal-content text-center">
            <div class="modal-header">
                <h4 class="modal-title">Assegnazione blocchetto</h4>
            </div>
            <div class="modal-body">
                <p>Vuoi assegnare il blocchetto?</p>
                @*@Html.LabelFor(model => model.CostCenter)
                    @Html.DropDownListFor(m => m.CostCenter, selectListItems, "HR")*@
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-primary" value="Assegna" />
                <input id="closeBtn" type="button" class="btn btn-primary" data-dismiss="modal" value="Chiudi"><!--close-->
            </div>
        </div>

    </div>
</div>